### ISSUE TITLE
COE should support max/min values

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#121]
The FMI standard (Section 2.2.3, Definition of Types of attached pdf) allows max/min values to be defined on reals/integers etc. The COE should handle FMUs which specify this information. 

[FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf](https://github.com/into-cps/intocps-ui/files/359603/FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf)

**Comment by lausdahl** [comment]
What is this about? The COE does nothing with min/max so it should have no impact on a simulation. So if this is about that the COE cannot simulate with these defined please provide an example since this sounds unlikely.

We are planning to add warning/errors if min or max is defined and not respected during simulation, but this has nothing with to do with the APP it will be runtime errors.

**Comment by ldcouto** [comment]
I think warnings are fine. Richard never mentioned anything about  the app.

Do any of our tools export FMUs with these limits?

**Comment by lausdahl** [comment]
I dont know but Dymola does.

**Comment by ldcouto** [comment]
I imagine Overture doesn't?

I personally think this is a useful feature to document and check restrictions on FMU signal. In fact, I originally asked Richard about it. When you have real multi-disciplinary teams, this kind of thing can trip you up easily.

**Comment by ldcouto** [comment]
This should be revisited after INTO-CPS. I still think it's a useful feature but we don't have the bandwidth to consider it right now.
