### ISSUE TITLE
Project Import and Export

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#13]
Exported projects are zipped up with the project.json file. And unzipped to import.

**Comment by lausdahl** [comment]
I think we need to discuss this:

- Import is somewhat strange since we dont have a workspace or any top level above a project so import is essentially just opening the project. Of cause we can make tool support to help the user unzip to a folder and then open the project after unzip completes. Is this what we want so shall the user just unzip and open.
- Export can be implemented as: 
 - full export, just zip the project
 - partial where the user can exclude elements of the project like in e.g. Eclipse

**Comment by ldcouto** [comment]
I think the main motivation for import/export is to support the importing of public examples, like in Symphony/Overture.

I'm fine with not providing an explicit import/export feature and the users can just (un)zip project folders with whatever program they want. But we would still need to bundle the (zipped) examples with the app and have an `Open Example` feature.

**Comment by lausdahl** [comment]
Ok to the export.

Maybe we should do the examples differently. The download manager already supports downloading and unzipping so we could just add example compendium or each single example to the release file and then let the user select them for install and open from there once downloaded and unzipped. - just an idea, since a few config lines in the release.json file will make this available now with no further changed.

**Comment by CarlGamble** [comment]
Hi,

I was wondering if we were going to have an eclipse style workspace and projects or if an INTO project would just standalone.  From a traceability point of view it could be easier if we just have standalone projects that the app clould open, then when it opens one it could inform the traceability daemon which project is open and then the daemon could store its data in a project specific store rather than in a single monolithic store for all projects.

Carl



On Sun, May 22, 2016 at 2:35 PM -0700, "Kenneth Lausdahl" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok to the export.

Maybe we should do the examples differently. The download manager already supports downloading and unzipping so we could just add example compendium or each single example to the release file and then let the user select them for install and open from there once downloaded and unzipped. - just an idea, since a few config lines in the release.json file will make this available now with no further changed.

> On 22 May 2016, at 23:27, Luis Diogo Couto <notifications@github.com> wrote:
>
> I think the main motivation for import/export is to support the importing of public examples, like in Symphony/Overture.
>
> I'm fine with not providing an explicit import/export feature and the users can just (un)zip project folders with whatever program they want. But we would still need to bundle the (zipped) examples with the app and have an Open Example feature.
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/into-cps/intocps-ui/issues/13#issuecomment-220857477>


-

**Comment by lausdahl** [comment]
We do not have a workspace. The App is designed to only handle one project at the time.

The traceability deamon, what is that suppose to be? You could just have whatever service that is being something the App hosts when a project is open. Or even better if you can make the merge stuff work be something that can run directly off the git repo so you dont need the App open locally.

**Comment by CarlGamble** [comment]
Hi

You are right it is currently going to be a process the app starts when it opens.  It provides the http port that receives all the oslc and prov data and stores it so we can query it later.  No decisions have been made yet about how it will function internally so we can talk about that in Linkoping and see what would work best.

I hace cc'd Twt here as i dont know if they are on the ui maillist.

Carl

Get Outlook for Android<https://aka.ms/ghei36>



On Sun, May 22, 2016 at 2:35 PM -0700, "Kenneth Lausdahl" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok to the export.

Maybe we should do the examples differently. The download manager already supports downloading and unzipping so we could just add example compendium or each single example to the release file and then let the user select them for install and open from there once downloaded and unzipped. - just an idea, since a few config lines in the release.json file will make this available now with no further changed.

> On 22 May 2016, at 23:27, Luis Diogo Couto <notifications@github.com> wrote:
>
> I think the main motivation for import/export is to support the importing of public examples, like in Symphony/Overture.
>
> I'm fine with not providing an explicit import/export feature and the users can just (un)zip project folders with whatever program they want. But we would still need to bundle the (zipped) examples with the app and have an Open Example feature.
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/into-cps/intocps-ui/issues/13#issuecomment-220857477>


-

**Comment by ldcouto** [comment]
I have mentioned this before but I think it would be useful to be able to
start the daemon without launching the app. If I'm working on my vdm model,
there is no need to open the app.

**Comment by CarlGamble** [comment]
Hi

I remember you saying that.

So i guess the options are.

1. Always start the app and this will launch the traceabiloty thread.

2.  Just start the traceability thread and inform it which project you are working on.  In this case why not start the app?

3. Have the modelling tools cache traceability data until the app is running. I don't know if this would work.

4.  Have the modelling tools write the oslc and prov data into a text file a stored somewhere in the project folders.  Then the app reads this when launched.

5  do something else entirely.

I wouldnt be too eorried about having to launch the app while modelling but if there is a strong steer in a different direction then we can find another solution.

Carl



On Mon, May 23, 2016 at 4:36 AM -0700, "Luis Diogo Couto" <notifications@github.com<mailto:notifications@github.com>> wrote:

I have mentioned this before but I think it would be useful to be able to
start the daemon without launching the app. If I'm working on my vdm model,
there is no need to open the app.
On 23 May 2016 08:39, "Carl Gamble" <notifications@github.com> wrote:

> Hi
>
> You are right it is currently going to be a process the app starts when it
> opens. It provides the http port that receives all the oslc and prov data
> and stores it so we can query it later. No decisions have been made yet
> about how it will function internally so we can talk about that in
> Linkoping and see what would work best.
>
> I hace cc'd Twt here as i dont know if they are on the ui maillist.
>
> Carl
>
> Get Outlook for Android<https://aka.ms/ghei36>
>
>
>
> On Sun, May 22, 2016 at 2:35 PM -0700, "Kenneth Lausdahl" <
> notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Ok to the export.
>
> Maybe we should do the examples differently. The download manager already
> supports downloading and unzipping so we could just add example compendium
> or each single example to the release file and then let the user select
> them for install and open from there once downloaded and unzipped. - just
> an idea, since a few config lines in the release.json file will make this
> available now with no further changed.
>
> > On 22 May 2016, at 23:27, Luis Diogo Couto <notifications@github.com>
> wrote:
> >
> > I think the main motivation for import/export is to support the
> importing of public examples, like in Symphony/Overture.
> >
> > I'm fine with not providing an explicit import/export feature and the
> users can just (un)zip project folders with whatever program they want. But
> we would still need to bundle the (zipped) examples with the app and have
> an Open Example feature.
> >
> > -
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub <
> https://github.com/into-cps/intocps-ui/issues/13#issuecomment-220857477>
>
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/into-cps/intocps-ui/issues/13#issuecomment-220857898>
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/into-cps/intocps-ui/issues/13#issuecomment-220908000>
>

-

**Comment by ldcouto** [comment]
For me, solutions 1 and 2 are disqualified since they require additional user input. We have to minimize this. 3 and 4 are fine by me, although I would be wary of crash recovery.

Speaking as a user, I don't particularly care about the implementation details. I just want to open whatever tool I need to do my work and for the traceability data to be collected automatically as much as possible. But perhaps this requirement is too ambitious.

As much as I dread it, we probably need to sit down at M18 and talk traceability once again :P. A concrete workflow (down to tool clicks) is probably needed.

--ldc

**Comment by lausdahl** [comment]
Please move this discussion to a differen issue this is about import/export of projects. So open another ticket for this discussion and continue there.

**Comment by ldcouto** [comment]
Right, sorry about that. I didn't notice we were still CC-ing the github address.

Back on-topic, I agree with your idea of using the download manager to handle the examples. So, if we use external archive tools, I suppose the project import/export task is mostly done. We can just describe what to do in the user manual.
