### ISSUE TITLE
COE hangs during initialisation

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#159]
The COE (version 0.1.2) hangs during initialisation of a co-sim. The COE finishes processing the config (the COE outputs the FMU paths, connections and parameters) and then won't proceed. No error messages are shown.

This may be an OM FMU issue, but I can't be sure - it occurs in the FCU pilot, with multi-model 4-model-OM, but not in 4-model.

**Comment by ldcouto** [comment]
Can you post the log of when it hangs? I experienced this behaviour with old-style VDM FMUs. Maybe some of the FCU pilot models haven't been re-exported?

**Comment by richardpayne** [comment]
The VDM FMU works ok - it works in another multi-model. I think it may be an OM issue - I have contacted LIU about it. I will post a log shortly anyway. I think it may be useful for the COE to produce an error warning/terminate however.

**Comment by ldcouto** [comment]
I can't reproduce this anymore partly because the 4-model MM has been removed.

In any case, I think it would be an interesting enhancement to giver the COE some kind of feature to cope with FMUs that hang during initialisation -- either timeouts or detection.

But I'd like to consider such an enhancement for post INTO-CPS.

@richardpayne , can you confirm that this no longer hangs?

**Comment by richardpayne** [comment]
Correct - no longer hangs - I think it was an OM FMU issue.
