### ISSUE TITLE
Connections mapping json generation

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#17]
From within Modelio, generate the connections mapping json file.

**Comment by ldcouto** [comment]
After some discussions by @lausdahl and @kgpierce we have decided to simplify the connections mapping export.

The connection export should only include connection information. It should not have any .fmu information whatsoever. The export must of course identify each component in a unique way (ideally with the name given to it by the user plus some minimal id info to make it unique.

@lausdahl , can you please post a sample .json file of how this new connection export must look?

**Comment by lausdahl** [comment]
I suggest we stay with the format used by the COE which we know Modelio already can generate. However, I think we should try to assist the user in specifying the correct FMU per connection, by adding some information to the FMU key like a block name or some path from the model that the user may be able to relate to.

```json
{
		"fmus":{
				"{x1}":"some info that can make the user relate to the sysml block this refers to when he has to select the FMU in the app. In this case the FMU which represents x1",
				"{x2}":"some info that can make the user relate to the sysml block this refers to when he has to select the FMU in the app. In this case the FMU which represents x2"
		},
		"connections":{
				"{x1}.controller.valve":["{x2}.tank.valvecontrol"],
				"{x2}.tank.level":["{x1}.controller.level"]
		},
		"parameters":{
				"{x1}.controller.maxlevel":2.5,
				"{x1}.controller.minlevel":2
		}
}
```

The format for the COE is described here: http://overture.au.dk/into-cps/site/simulation/example.html

Format: `{x1}.controller.valve` this is `'{' + [key] + '}' + '.' + [instance name] + '.' + [scalar variable name]`

- **key** essentially the key `{x1}` is linked to an FMU by path, or in this case a description so the App UI can let the user specify the path from within the project.
- **instance name** generated name to enable multiple instances of the same FMU (required by the standard)
- **scalar variable name** the name of an scalar variable in the FMU's `modelDescription.xml` this will be `input`, `output` or `parameter`.

This format is what Modelio generates for the COE at the moment. The only change is that the path for the key is optional, but we would suggest a user hint.

The demo I made assumes this input and the file named `*.sysml.json`, and written to a location inside the Modelio project.

**Comment by etiennebrosse** [comment]
Agreed, concerning the additional information we will define it during Stuttgart meeting

________________________________

**Comment by etiennebrosse** [comment]
Solved with the 1.0.28 version of INTO-CPS extension http://forge.modelio.org/projects/intocps-modelio34/files

The file is saved at the $ModelioProject /Simulation/cofiguration/*.sysml.json path

**Comment by lausdahl** [comment]
The site seems to be offline, or not browsable using a web browser.

**Comment by etiennebrosse** [comment]
Should be better now...

**Comment by lausdahl** [comment]
Feedback for version 1.0.28:

Since I’m not an expert in SysML I will give some feedback from the users point of view.

I think the generate configuration should be moved onto the “connection diagram”, and check the terminology to use the right name nere.
If possible then I think you should try to automatically name the exported configuration with the name of the “connection diagram” 
concerning the output location, unless the path Simulation/configs/ is needed I would suggest to drop “configs” then there is less folders to browse in the App. If thats not the case we can modify the app to flatten the SysML folder structure and show all exported configs at the top-level. What do you think?
remove the COE.jar

otherwise it looked like it worked with the HEAD of into-cps-ui

**Comment by etiennebrosse** [comment]
I am fine with the location.
Concerning the automated name I would use the name of the diagram as default instead of "configuration" but I would keep the possibility to change the name as it is now and add the list of parameter to be able to change the start value.
Concerning moving the command from the block instance to connection diagram, I would have both a generation from the block instance and from a diagram. A generation from a diagram could be see as more intuitive in our small example in a real example your system will be modelled thanks to several diagram. In this case, I can imagne a configuration generation from one specific view (aka diagram) or for the whole system so from the system element.
Any feedback?

BTW what do you mean by remove the COE.jar?

**Comment by lausdahl** [comment]
ok

yes remove the COE.jar. We want to use the INTO-CPS-Application for managing the tools. So please remove it from inside Modelio otherwise we might get into trouble where the user ends up running an old version of the COE. This should also make the Modelio release simpler.

**Comment by etiennebrosse** [comment]
Ok I see I will clean the projects to remove old artefacts

**Comment by ldcouto** [comment]
This seems done. Can I close this issue?

**Comment by lausdahl** [comment]
INTO-CPS extension *30 and 9e44e00c7f253fa72df18658ce593fe852eaa82f fixes this issue
