### ISSUE TITLE
Better documentation of user settings

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#263]
The settings page has a growing number of options. These are not documented at all. There are various paths that must be set where it's not clear what the path should be

At a minimum, these options should be explained in the manual. I'd also like for the path-based stuff to go from text box to file browser dialog.

**Comment by bandurvp** [comment]
Hi @ldcouto , is it OK if I change the setting names containing underscores to something nicer, like the RT-Tester ones?

**Comment by ldcouto** [comment]
In the view? Go right ahead, as long as those names aren't being used for lookups or something

**Comment by ldcouto** [comment]
And please use the branch from #263 so we coordinate everything there.

**Comment by lausdahl** [comment]
@bandurvp be careful because what you see there is the actual keys so do not change these it breaks backwards compatibility with old workspaces. If you want to then implement a function that beautifies the key names and use it for display. It might be good to keep the key name visible for reference with the `settings.json`

**Comment by bandurvp** [comment]
@ldcouto , @lausdahl I had started out by documenting these in the user manual, but the help popup approach is easy to understand for the user and I don't think anything further is required in the user manual.  I'll just try to do the beautification instead.

**Comment by ldcouto** [comment]
Sounds good. Just mention the help popup in the user manual
