### ISSUE TITLE
Cannot rerun co-sims on changed multimodels

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#265]
I guess this is related to the "validity" of co-sims feature (maybe #222)

But this implementation is too restrictive. We can flag the results as invalid/issue a warning but forcing users to create a new co-sim every-time they change a multi-model is too restrictive. Especially because we can't duplicate co-sims so there is lots of re-clicking.

This feature needs to be disabled

**Comment by ldcouto** [comment]
That is definitely not the case. It prevents launching co-sims.

**Comment by ldcouto** [comment]
We can either merge #266 or update the error message to explain how to regenerate the checksum. But right now, it's very unintuitive behavior.

**Comment by lausdahl** [comment]
It was implemented to prevent co-simulations if the multi model changed since a change here should be done in Modelio and then re-exported to the app as a new multi-model (except for the selection of the FMUs). With this in mind I think updating the error message might be best.

I understand why you want this disabled since your workflow is based on a standard iterative development workflow (which I also prefer) but there was a strong focus on the fact that configs and results no longer was valid if something changed. If you want it removed I suggest bringing it up at the meeting for WP4. (personally I'm ok with either solution)

**Comment by ldcouto** [comment]
Thanks.

I think it's not worth the discussion. I'll just update the error message.
