### ISSUE TITLE
Cannot dblick, right click or expand nodes

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#47]
I just pulled the latest master and added the test project.
I cannot dblClick - error: `Uncaught TypeError: Cannot read property 'dblClickHandler' of null`,
I cannot expand the nodes - no error,
I cannot right click: `Uncaught TypeError: Cannot read property 'menuEntries' of null`

First come first serve to fix the bug :D

**Comment by FlorianLapschies** [comment]
Each node of the w2sidebar has to have a unique id attribute. Before, we used the path of the file system object it represents. As it turns out, these ids cannot have an arbitrary format. Especially windows file system paths caused trouble. This resulted in a failure when using the ids to lookup the node.
